### PR TITLE
Add note for installing Minikube vs Minishift vs Openshift

### PR DESCRIPTION
**Pull request by aliok**
Added some short text explaining that either Minishift or Minukube is good.

When I did the tutorial, I thought there are some parts specific to OpenShift/Minishift in the later chapters as minishift is also listed in the prereqs in addition to minikube. Tried to get rid of this confusion in this PR.

### CODE REVIEW

**Comment by kameshsampath** [comment]
@aliok this is a big debate happening and here is what we thought of. Minikube will be preferred for upsteam as tutorial targets the upstream knative. We will have to revisit he OpenShift install once we have OpenShift 4 GA + an option for developer to run OpenShift 4 locally, which is still undecided.

**Comment by matzew** [comment]
FWIW, I have minishift/3.11 running w/ Knative 0.5.0  - but yeah, it's tricky w/ regards to Openshift4 / installer

**Comment by aliok** [comment]
@kameshsampath understood. feel free to merge or close this PR.

**Comment by kameshsampath** [comment]
@aliok  - please check the latest master I made some refactors and also cherry picked your v0.5.0 commits into it. Would you mind rebasing your other PRs with the latest ?

**Comment by aliok** [comment]
@kameshsampath Rebased PR --> https://github.com/redhat-developer-demos/knative-tutorial/pull/156

**Pull request closed without merging**
