### PR TITLE
Update Camel-K examples for use with Camel-K version 1.0.0-M1

### PR DESCRIPTION
**Pull request by lubuxnl**
The tutorial uses Knative v0.7.1. According to this Camel-K [issue](https://github.com/apache/camel-k/issues/919) the compatible Camel-K version for this Knative version is 1.0.0-M1. The instructions for the Camel-K examples need some editing too, but the sources for these web pages doesn't seem to be in a Git repo?!

### CODE REVIEW

**Comment by kameshsampath** [comment]
@lubuxnl  - thanks for the PR the docs for the camel-k is https://github.com/redhat-developer-demos/knative-tutorial-module-camelk

**Comment by kameshsampath** [comment]
I will take review soon

**Comment by lubuxnl** [comment]
Thanks for the links to the documentation @kameshsampath 
Actually I am still in doubt whether it's a good idea to switch to Camel-K 1.0.0-M1, because of an issue I found with this version. I [reported](https://github.com/apache/camel-k/issues/923) this on the Camel-K repository, but unfortunately it hasn't been solved yet. I did find a workaround however (using the integration kit for one example as input for another example), but that would introduce a dependency between the examples, especially between the cartoon message mover and cartoon message downloader. Is this a problem? An alternative solution would be to 'downgrade' the Knative version in the tutorial to the recommended version for Camel-K 0.3.3. What's your opinion on this?

**Comment by kameshsampath** [comment]
@lubuxnl do you still want to do this? would you mind sending a new PR to https://github.com/redhat-developer-demos/knative-tutorial-module-camelk ? I will be adding a `1.0.0-M1` branch to camel-k soon .

**Pull request closed without merging**
